const teams = {
  Brazil:{zh:"巴西",code:"BRA",group:"C",formation:"4-3-3",style:"边路爆点多，前场压迫强，定位球防守需谨慎。",stars:["Vinicius Junior","Rodrygo","Bruno Guimaraes"],attack:94,midfield:88,defense:84,form:84,depth:90,baseXg:2.15},
  Haiti:{zh:"海地",code:"HAI",group:"C",formation:"5-4-1",style:"低位防守，依赖反击和二点球，控球推进偏弱。",stars:["Duckens Nazon","Frantzdy Pierrot","Jean-Ricner Bellegarde"],attack:64,midfield:61,defense:59,form:62,depth:55,baseXg:.78},
  Scotland:{zh:"苏格兰",code:"SCO",group:"C",formation:"3-4-2-1",style:"身体对抗强，边翼卫推进明确，中路创造力依赖核心状态。",stars:["Scott McTominay","Andrew Robertson","John McGinn"],attack:74,midfield:78,defense:76,form:73,depth:70,baseXg:1.22},
  Morocco:{zh:"摩洛哥",code:"MAR",group:"C",formation:"4-1-4-1",style:"防线纪律强，边路转换快，适合打强队身后空间。",stars:["Achraf Hakimi","Sofyan Amrabat","Youssef En-Nesyri"],attack:78,midfield:80,defense:84,form:81,depth:76,baseXg:1.34},
  Turkiye:{zh:"土耳其",code:"TUR",group:"D",formation:"4-2-3-1",style:"前腰和边锋创造力强，节奏高，防守转换有波动。",stars:["Hakan Calhanoglu","Arda Guler","Kenan Yildiz"],attack:81,midfield:82,defense:73,form:78,depth:75,baseXg:1.48},
  Paraguay:{zh:"巴拉圭",code:"PAR",group:"D",formation:"4-4-2",style:"防守韧性和空中对抗好，进攻依赖定位球和二次进攻。",stars:["Miguel Almiron","Julio Enciso","Gustavo Gomez"],attack:73,midfield:72,defense:78,form:74,depth:70,baseXg:1.12},
  USA:{zh:"美国",code:"USA",group:"D",formation:"4-3-3",style:"跑动覆盖大，边路速度明显，主场环境提升压迫强度。",stars:["Christian Pulisic","Weston McKennie","Tyler Adams"],attack:80,midfield:79,defense:77,form:80,depth:78,baseXg:1.52},
  Australia:{zh:"澳大利亚",code:"AUS",group:"D",formation:"4-4-1-1",style:"防守组织稳定，身体对抗强，阵地战破密集效率一般。",stars:["Jackson Irvine","Harry Souttar","Mathew Ryan"],attack:69,midfield:71,defense:75,form:72,depth:68,baseXg:1.03},
  Germany:{zh:"德国",code:"GER",group:"E",formation:"4-2-3-1",style:"中前场技术密度高，阵地战强，防线身后空间需控制。",stars:["Jamal Musiala","Florian Wirtz","Joshua Kimmich"],attack:88,midfield:90,defense:80,form:83,depth:86,baseXg:1.82},
  CIV:{zh:"科特迪瓦",code:"CIV",group:"E",formation:"4-3-3",style:"个人冲击力强，转换速度快，防线协同影响上限。",stars:["Sebastien Haller","Franck Kessie","Simon Adingra"],attack:77,midfield:76,defense:72,form:79,depth:73,baseXg:1.28},
  Netherlands:{zh:"荷兰",code:"NED",group:"F",formation:"3-4-2-1",style:"三中卫出球稳定，定位球强，前场终结效率决定上限。",stars:["Virgil van Dijk","Frenkie de Jong","Xavi Simons"],attack:84,midfield:84,defense:87,form:82,depth:82,baseXg:1.62},
  Sweden:{zh:"瑞典",code:"SWE",group:"F",formation:"4-4-2",style:"前锋支点明确，长传和边路传中直接，防线移动速度是风险点。",stars:["Alexander Isak","Dejan Kulusevski","Viktor Gyokeres"],attack:82,midfield:76,defense:74,form:77,depth:74,baseXg:1.42}
};

let matches = [
  {id:"bra-hai",date:"2026-06-19",time:"待确认",group:"C",venue:"Philadelphia Stadium",home:"Brazil",away:"Haiti",stakes:"巴西争取提前锁定出线主动权；海地需要控制净胜球，第三名排名也会受影响。",odds:{h:1.12,d:6.8,a:18,o:1.58,u:2.15,ht:2.75}},
  {id:"sco-mar",date:"2026-06-19",time:"待确认",group:"C",venue:"Boston Stadium",home:"Scotland",away:"Morocco",stakes:"C组第二名关键战，胜者大概率占据直接晋级位置，败者可能被迫计算第三名积分。",odds:{h:3.05,d:3.05,a:2.25,o:2.08,u:1.62,ht:1.95}},
  {id:"tur-par",date:"2026-06-19",time:"待确认",group:"D",venue:"San Francisco Bay Area Stadium",home:"Turkiye",away:"Paraguay",stakes:"D组中游对冲战，平局会让最后一轮压力上升，胜者接近前二。",odds:{h:2.18,d:3.1,a:3.15,o:1.92,u:1.76,ht:2.02}},
  {id:"usa-aus",date:"2026-06-19",time:"待确认",group:"D",venue:"Seattle Stadium",home:"USA",away:"Australia",stakes:"美国主场优势明显，若取胜将大幅提升小组前二概率；澳大利亚需要降低比赛回合数。",odds:{h:1.82,d:3.35,a:4.05,o:1.88,u:1.82,ht:2.08}},
  {id:"ger-civ",date:"2026-06-20",time:"待确认",group:"E",venue:"Toronto Stadium",home:"Germany",away:"CIV",stakes:"德国控球优势明显，但科特迪瓦转换速度会测试德国防线身后保护。",odds:{h:1.62,d:3.65,a:5.1,o:1.72,u:1.98,ht:2.22}},
  {id:"ned-swe",date:"2026-06-20",time:"待确认",group:"F",venue:"Houston Stadium",home:"Netherlands",away:"Sweden",stakes:"荷兰控场与瑞典双前锋冲击的对比明显，定位球可能改变胜负概率。",odds:{h:1.88,d:3.25,a:3.85,o:1.95,u:1.75,ht:2.05}}
];

let state = {date: matches[0].date, id: matches[0].id};
let scheduleMeta = {source:"本地演示赛程", updatedAt:null, fallback:true};
const $ = (selector) => document.querySelector(selector);
const pct = (value) => `${(value * 100).toFixed(1)}%`;
const clamp = (value, min, max) => Math.max(min, Math.min(max, value));

function factorial(n){let result = 1; for(let i = 2; i <= n; i += 1) result *= i; return result;}
function poisson(lambda, goals){return Math.exp(-lambda) * Math.pow(lambda, goals) / factorial(goals);}
function currentMatch(){return matches.find((match) => match.id === state.id) || matches[0];}
function expectedGoals(match){const h = teams[match.home], a = teams[match.away]; const edge = match.home === "USA" ? .18 : .08; return {h: clamp(h.baseXg + (h.attack - a.defense) / 52 + (h.form - a.form) / 95 + edge, .25, 3.6), a: clamp(a.baseXg + (a.attack - h.defense) / 55 + (a.form - h.form) / 100, .2, 3.2)};}
function model(match){const xg = expectedGoals(match); const scores = []; let h = 0, d = 0, a = 0, over = 0, bts = 0; for(let home = 0; home <= 6; home += 1){for(let away = 0; away <= 6; away += 1){const p = poisson(xg.h, home) * poisson(xg.a, away); scores.push({score:`${home}-${away}`, p}); if(home > away) h += p; else if(home === away) d += p; else a += p; if(home + away > 2.5) over += p; if(home && away) bts += p;}} const covered = scores.reduce((sum, item) => sum + item.p, 0); return {xg, h:h/covered, d:d/covered, a:a/covered, over:over/covered, bts:bts/covered, scores:scores.sort((x,y)=>y.p-x.p).slice(0,5)};}
function readOdds(){return {h:+$("#oH").value,d:+$("#oD").value,a:+$("#oA").value,o:+$("#oO").value,u:+$("#oU").value,ht:+$("#oHT").value};}
function implied(odds){const raw = {h:1/odds.h,d:1/odds.d,a:1/odds.a}; const total = raw.h + raw.d + raw.a; return {h:raw.h/total,d:raw.d/total,a:raw.a/total,margin:total-1};}
function normalizeRemoteSchedule(payload){const rows = Array.isArray(payload) ? payload : payload.matches; if(!Array.isArray(rows)) return []; return rows.map((item, index)=>{const homeKey = item.homeKey || item.home || item.homeTeam || `RemoteHome${index}`; const awayKey = item.awayKey || item.away || item.awayTeam || `RemoteAway${index}`; if(!teams[homeKey]) teams[homeKey] = {zh:item.homeName || item.home || homeKey,code:String(homeKey).slice(0,3).toUpperCase(),group:item.group || "竞彩",formation:item.homeFormation || "待确认",style:item.homeStyle || "赛前阵容、伤停和风格需结合实时情报确认。",stars:item.homeStars || ["首发待确认"],attack:item.homeAttack || 72,midfield:item.homeMidfield || 72,defense:item.homeDefense || 72,form:item.homeForm || 72,depth:item.homeDepth || 70,baseXg:item.homeXg || 1.25}; if(!teams[awayKey]) teams[awayKey] = {zh:item.awayName || item.away || awayKey,code:String(awayKey).slice(0,3).toUpperCase(),group:item.group || "竞彩",formation:item.awayFormation || "待确认",style:item.awayStyle || "赛前阵容、伤停和风格需结合实时情报确认。",stars:item.awayStars || ["首发待确认"],attack:item.awayAttack || 72,midfield:item.awayMidfield || 72,defense:item.awayDefense || 72,form:item.awayForm || 72,depth:item.awayDepth || 70,baseXg:item.awayXg || 1.2}; return {id:item.id || `${homeKey}-${awayKey}-${item.date || ""}`.toLowerCase().replace(/[^a-z0-9-]/g,"-"),date:item.date || new Date().toISOString().slice(0,10),time:item.time || "待确认",group:item.group || "竞彩",venue:item.venue || item.league || "体彩开放赛事",home:homeKey,away:awayKey,stakes:item.stakes || "自动更新赛程，阵容与盘口需临场复核。",odds:{h:+(item.odds?.h || item.h || item.win || 2.1),d:+(item.odds?.d || item.d || item.draw || 3.1),a:+(item.odds?.a || item.a || item.loss || 3.2),o:+(item.odds?.o || item.o || item.over || 1.9),u:+(item.odds?.u || item.u || item.under || 1.85),ht:+(item.odds?.ht || item.ht || item.halfDraw || 2.05)}};}).filter((item)=>item.home && item.away);}
async function loadSchedule(){try{const response = await fetch("/api/schedule",{cache:"no-store"}); if(!response.ok) throw new Error(`HTTP ${response.status}`); const payload = await response.json(); const remote = normalizeRemoteSchedule(payload); scheduleMeta = {source:payload.source || "远程赛程源", updatedAt:payload.updatedAt || new Date().toISOString(), fallback:!remote.length, message:payload.message || ""}; if(remote.length){matches = remote; state.date = matches[0].date; state.id = matches[0].id; render();}}catch(error){scheduleMeta = {...scheduleMeta, fallback:true, message:`实时赛程暂未更新：${error.message}`};}}

function renderDates(){const dates = [...new Set(matches.map((match)=>match.date))]; $("#dateSelect").innerHTML = dates.map((date)=>`<option value="${date}">${date}</option>`).join(""); $("#dateSelect").value = state.date;}
function renderMatchList(){const list = matches.filter((match)=>match.date === state.date); if(!list.length){$("#matchList").innerHTML = `<div class="note">今日暂无可用赛程。${scheduleMeta.message || ""}</div>`; return;} if(!list.some((match)=>match.id === state.id)) state.id = list[0].id; const status = `<div class="schedule-status ${scheduleMeta.fallback?"warn":"ok"}">赛程源：${scheduleMeta.source}${scheduleMeta.updatedAt ? ` · ${new Date(scheduleMeta.updatedAt).toLocaleString()}` : ""}${scheduleMeta.message ? `<br>${scheduleMeta.message}` : ""}</div>`; $("#matchList").innerHTML = status + list.map((match)=>`<button class="match ${match.id===state.id?"active":""}" data-id="${match.id}"><strong>${teams[match.home].zh} vs ${teams[match.away].zh}</strong><span>${match.group}组 · ${match.venue}</span><span>${match.stakes}</span></button>`).join("");}
function setOdds(match){$("#oH").value=match.odds.h;$("#oD").value=match.odds.d;$("#oA").value=match.odds.a;$("#oO").value=match.odds.o;$("#oU").value=match.odds.u;$("#oHT").value=match.odds.ht;}
function renderOddsText(md){const odds = readOdds(); if([odds.h, odds.d, odds.a].some((value)=>!value || value <= 1)){ $("#oddsText").textContent = "请输入有效赔率。"; return;} const market = implied(odds); const gap = [["主胜", md.h-market.h],["平局", md.d-market.d],["客胜", md.a-market.a]].sort((x,y)=>y[1]-x[1]); const overMarket = odds.o && odds.u ? (1/odds.o)/(1/odds.o+1/odds.u) : 0; $("#oddsText").innerHTML = `赔率隐含：主胜 ${pct(market.h)}、平局 ${pct(market.d)}、客胜 ${pct(market.a)}；水位约 ${(market.margin*100).toFixed(1)}%。<br>模型差最大：${gap[0][0]} ${gap[0][1]>=0?"+":""}${(gap[0][1]*100).toFixed(1)} 个百分点。${overMarket ? `<br>大2.5 隐含 ${pct(overMarket)}，泊松模型 ${pct(md.over)}。` : ""}`;}
function statBars(team){const labels = {attack:"进攻", midfield:"中场", defense:"防守", form:"状态", depth:"深度"}; return Object.keys(labels).map((key)=>`<div class="bar"><span>${labels[key]}</span><span class="track"><span class="fill" style="width:${team[key]}%"></span></span><span>${team[key]}</span></div>`).join("");}
function renderAIModels(home, away, md, choices){const strength = (home.attack+home.midfield+home.defense+home.form+away.attack+away.midfield+away.defense+away.form)/8; const caution = md.d > .27 ? "平局权重偏高，建议复核半场和小球赔率。" : "胜负方向较清晰，重点复核临场首发。"; const cards = [["K3本地泊松","已启用",`${choices[0].label} ${pct(choices[0].value)}`,`基于预期进球 ${md.xg.h.toFixed(2)}-${md.xg.a.toFixed(2)}、比分矩阵和赔率差值生成。`],["Qwen 千问","连接中","等待服务端返回","用于中文赛事情报、伤停摘要、球队新闻结构化。"],["DeepSeek","连接中","等待服务端返回","用于赔率异动、凯利风险和策略解释交叉检查。"]]; return cards.map((card)=>`<div class="ai-card ${card[1]!=="已启用"?"pending":""}" data-ai-card="${card[0]}"><h3>${card[0]}<em>${card[1]}</em></h3><strong>${card[2]}</strong><p>${card[3]}</p><p>${caution} 综合强度指数 ${strength.toFixed(1)}。</p></div>`).join("");}
async function refreshAIAnalysis(match, home, away, md, choices){try{const response=await fetch("/api/ai-analysis",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({match:{id:match.id,date:match.date,group:match.group,venue:match.venue,stakes:match.stakes},home:{name:home.zh,formation:home.formation,style:home.style,stars:home.stars},away:{name:away.zh,formation:away.formation,style:away.style,stars:away.stars},model:{pick:choices[0].label,probability:choices[0].value,xg:md.xg,over25:md.over,bts:md.bts,topScores:md.scores},odds:readOdds(),samples:getSamples().filter(s=>s.matchId===match.id).slice(-8)})});const data=await response.json();for(const item of data.results||[]){const card=document.querySelector(`[data-ai-card="${item.provider}"]`);if(card){card.classList.toggle("pending",!item.ok);card.innerHTML=`<h3>${item.provider}<em>${item.ok?"已接入":"未可用"}</em></h3><strong>${item.pick||"暂无结论"}</strong><p>${item.analysis||item.error||"服务端未返回内容。"}</p>`;}}}catch(error){for(const provider of ["Qwen 千问","DeepSeek"]){const card=document.querySelector(`[data-ai-card="${provider}"]`);if(card){card.classList.add("pending");card.innerHTML=`<h3>${provider}<em>连接失败</em></h3><strong>服务端不可用</strong><p>${error.message}</p>`;}}}}

let monitorTimer = null;
function parseResultScore(text){const m=String(text||"").trim().match(/^(\d+)\s*[-:]\s*(\d+)$/); return m?{home:+m[1],away:+m[2]}:null;}
function outcomeFromScore(score){if(!score)return null; return score.home>score.away?"h":score.home===score.away?"d":"a";}
function trainFromSamples(){const done=getSamples().filter(s=>s.result); if(!done.length)return null; let marketHit=0,poissonHit=0; for(const s of done){const marketPick=Object.entries(s.odds).filter(([k])=>["h","d","a"].includes(k)).sort((a,b)=>a[1]-b[1])[0]?.[0]; if(marketPick===s.result)marketHit+=1; if(s.modelPick===s.result)poissonHit+=1;} const marketRate=marketHit/done.length, poissonRate=poissonHit/done.length; const market=Math.round(20+marketRate*45); const poisson=Math.round(20+poissonRate*45); const team=Math.max(10,100-market-poisson); return {count:done.length,marketRate,poissonRate,weights:{market,poisson,team}};}
function applyTrainedWeights(){const trained=trainFromSamples(); if(!trained)return; $("#wMarket").value=trained.weights.market; $("#wPoisson").value=trained.weights.poisson; $("#wTeam").value=trained.weights.team;}
function saveMatchResult(){const score=parseResultScore($("#resultScore")?.value); const result=outcomeFromScore(score); if(!result){alert("请输入正确赛果，例如 2-1"); return;} const match=currentMatch(); const samples=getSamples(); const last=[...samples].reverse().find(s=>s.matchId===match.id); if(last){last.score=score; last.result=result;} else {samples.push({time:Date.now(),matchId:match.id,odds:readOdds(),result,score});} setSamples(samples); applyTrainedWeights(); renderMain();}
function toggleMonitor(){const btn=$("#toggleMonitor"); if(monitorTimer){clearInterval(monitorTimer); monitorTimer=null; if(btn)btn.textContent="开始监控"; return;} recordCurrentOdds(); const seconds=Math.max(5,+$("#monitorSeconds")?.value||30); monitorTimer=setInterval(()=>{recordCurrentOdds(true);},seconds*1000); if(btn)btn.textContent="停止监控";}
function kellyFraction(probability, decimalOdds){const b=decimalOdds-1; if(!b || b<=0) return 0; return Math.max(0,(b*probability-(1-probability))/b);}
function getSamples(){try{return JSON.parse(localStorage.getItem("k3OddsSamples")||"[]");}catch{return [];}}
function setSamples(samples){localStorage.setItem("k3OddsSamples",JSON.stringify(samples.slice(-300)));}
function readWeights(){return {market:+$("#wMarket")?.value||35, poisson:+$("#wPoisson")?.value||35, team:+$("#wTeam")?.value||30};}
function renderAdvancedAnalytics(match, home, away, md, choices){
  const odds = readOdds();
  const hLine = +$("#handicapLine")?.value || 0;
  const hHome = +$("#handicapHome")?.value || 1.9;
  const hAway = +$("#handicapAway")?.value || 1.9;
  const fav = choices[0];
  const handicapLean = hLine < 0 ? `${home.zh}让 ${Math.abs(hLine)}` : hLine > 0 ? `${away.zh}让 ${Math.abs(hLine)}` : "平手盘";
  const handicapImpliedHome = (1/hHome)/((1/hHome)+(1/hAway));
  $("#handicapText").innerHTML = `${handicapLean}；盘口隐含主队方向 ${pct(handicapImpliedHome)}，泊松主胜 ${pct(md.h)}。`;
  const kellyItems = [[`${home.zh}胜`,md.h,odds.h],["平局",md.d,odds.d],[`${away.zh}胜`,md.a,odds.a]];
  $("#kellyGrid").innerHTML = kellyItems.map(([label,p,o])=>`<div class="kelly-cell"><span>${label}</span><b>${pct(kellyFraction(p,o))}</b><span>赔率 ${o || "-"}</span></div>`).join("");
  const samples = getSamples();
  const matchSamples = samples.filter(s=>s.matchId===match.id);
  const last = matchSamples.at(-1);
  const move = last ? `较上次：主胜 ${((odds.h-last.odds.h)||0).toFixed(2)}，平局 ${((odds.d-last.odds.d)||0).toFixed(2)}，客胜 ${((odds.a-last.odds.a)||0).toFixed(2)}` : "暂无上一条样本";
  const trained=trainFromSamples(); const threshold=+$("#moveThreshold")?.value||0.08; const isAlert=last && Math.max(Math.abs(odds.h-last.odds.h||0),Math.abs(odds.d-last.odds.d||0),Math.abs(odds.a-last.odds.a||0))>=threshold; $("#dataStats").innerHTML = `总样本 ${samples.length} 条；本场 ${matchSamples.length} 条。${move}${trained?`<br>训练样本 ${trained.count} 条；盘口命中 ${(trained.marketRate*100).toFixed(1)}%，泊松命中 ${(trained.poissonRate*100).toFixed(1)}%。建议权重：盘口 ${trained.weights.market} / 泊松 ${trained.weights.poisson} / 阵容 ${trained.weights.team}`:""}${isAlert?`<div class="monitor-alert">赔率变化超过阈值 ${threshold.toFixed(2)}，建议复核盘口。</div>`:""}`;
  const weights = readWeights();
  const total = weights.market + weights.poisson + weights.team;
  const selectedOdd = fav.label === `${home.zh}胜` ? odds.h : fav.label === "平局" ? odds.d : odds.a;
  const marketSignal = 1 / Math.max(1.01, selectedOdd || 2);
  const poissonSignal = fav.value;
  const teamSignal = (home.attack+home.midfield+home.defense+away.attack+away.midfield+away.defense)/600;
  const score = ((weights.market*marketSignal)+(weights.poisson*poissonSignal)+(weights.team*teamSignal))/total;
  $("#trainingText").innerHTML = `策略评分 ${(score*100).toFixed(1)}；当前建议：${score>.48?"可进入重点观察池":"等待赔率或阵容确认"}。持续记录样本后，可用于回测权重。`;
  $("#oddsHistory").innerHTML = matchSamples.slice(-6).reverse().map(s=>`<div class="history-row"><b>${new Date(s.time).toLocaleTimeString()}</b><span>主 ${s.odds.h}</span><span>平 ${s.odds.d}</span><span>客 ${s.odds.a}</span></div>`).join("") || '<div class="note">暂无本场历史样本，点击“记录当前赔率”开始收集。</div>';
}
function recordCurrentOdds(silent=false){const match=currentMatch(); const md=model(match); const choices=[{key:"h",value:md.h},{key:"d",value:md.d},{key:"a",value:md.a}].sort((a,b)=>b.value-a.value); const samples=getSamples(); const current={time:Date.now(),matchId:match.id,odds:readOdds(),modelPick:choices[0].key,handicap:{line:+$("#handicapLine").value,home:+$("#handicapHome").value,away:+$("#handicapAway").value}}; samples.push(current); setSamples(samples); if(!silent)renderMain(); else renderMain();}
function exportSamples(){const blob=new Blob([JSON.stringify(getSamples(),null,2)],{type:"application/json"}); const url=URL.createObjectURL(blob); const a=document.createElement("a"); a.href=url; a.download="k3-odds-samples.json"; a.click(); URL.revokeObjectURL(url);}
function clearSamples(){setSamples([]); renderMain();}
function renderMain(){const match = currentMatch(); const home = teams[match.home], away = teams[match.away], md = model(match); const choices = [{label:`${home.zh}胜`,value:md.h},{label:"平局",value:md.d},{label:`${away.zh}胜`,value:md.a}].sort((x,y)=>y.value-x.value); $("#heroPick").textContent = `${choices[0].label} ${pct(choices[0].value)}`; $("#heroText").textContent = `${home.zh} vs ${away.zh}，最高概率比分 ${md.scores[0].score}。`; $("#meta").textContent = `${match.date} · ${match.group}组 · ${match.venue} · ${match.time}`; $("#title").textContent = `${home.zh} vs ${away.zh}`; $("#context").textContent = match.stakes; $("#pick").textContent = `${choices[0].label} ${pct(choices[0].value)}`; $("#xg").textContent = `${md.xg.h.toFixed(2)} - ${md.xg.a.toFixed(2)}`; $("#over25").textContent = pct(md.over); $("#pH").textContent = pct(md.h); $("#pD").textContent = pct(md.d); $("#pA").textContent = pct(md.a); $("#scores").innerHTML = md.scores.map((item)=>`<div class="score"><b>${item.score}</b><span>${pct(item.p)}</span></div>`).join(""); setOdds(match); renderOddsText(md); $("#compare").innerHTML = `<div class="section-head"><h2>阵容与风格</h2><p>阵型和核心球员为赛前分析口径，正式首发需赛前确认。</p></div><div class="compare">${[home,away].map((team)=>`<div class="team"><header><div><h3>${team.zh}</h3><p>${team.formation} · ${team.style}</p></div><div class="badge">${team.code}</div></header>${statBars(team)}<ul class="bullets">${team.stars.map((star)=>`<li>${star}</li>`).join("")}</ul></div>`).join("")}</div>`; $("#path").innerHTML = `<div class="section-head"><h2>晋级路径</h2><p>48队分12组，每组前二和8个最佳第三进入32强。</p></div><div class="advance"><div class="metric"><span>本场关键</span><strong>${choices[0].label}更占优</strong></div><div class="metric"><span>小组影响</span><strong>${md.d>.27?"平局概率偏高，第三名积分和净胜球权重上升。":"胜负倾向较清晰，胜者更接近小组前二。"}</strong></div><div class="metric"><span>32强推理</span><strong>${match.group}组前二进入固定32强路径；第三名对手取决于8个最佳第三组合。</strong></div><div class="metric"><span>赛程风险</span><strong>短间隔比赛下，阵容深度和轮换能力会提高权重。</strong></div></div>`; $("#aiGrid").innerHTML = renderAIModels(home, away, md, choices); refreshAIAnalysis(match, home, away, md, choices); renderAdvancedAnalytics(match, home, away, md, choices); $("#reason").innerHTML = [["胜负",`首选 ${choices[0].label}。预期进球 ${home.zh} ${md.xg.h.toFixed(2)}，${away.zh} ${md.xg.a.toFixed(2)}。`],["比分",`最高概率比分 ${md.scores[0].score}，其次 ${md.scores.slice(1,3).map((item)=>item.score).join("、")}。`],["半场",`半场进球按全场约45%估算，半场平局通常高于全场平局，需单独校验半场赔率。`],["梦想单",`大2.5概率 ${pct(md.over)}，双方进球概率 ${pct(md.bts)}；赔率差异较大时优先复查实时盘口。`]].map((item)=>`<div class="reason-card"><h3>${item[0]}</h3><p>${item[1]}</p></div>`).join("");}
function render(){renderDates(); renderMatchList(); renderMain(); refreshAccess();}

function isActivated(){return localStorage.getItem("k3Activated") === "1";}
function refreshAccess(){const predict = $("#predict"); const btn = $("#accountBtn"); if(!predict || !btn) return; predict.classList.toggle("locked", !isActivated()); btn.textContent = isActivated() ? "已开通" : "登录/充值";}
function openAuth(){const dialog = $("#authDialog"); if(dialog) dialog.showModal();}

$("#dateSelect").addEventListener("change", (event)=>{state.date = event.target.value; state.id = matches.find((match)=>match.date === state.date).id; render();});
$("#matchList").addEventListener("click", (event)=>{const button = event.target.closest(".match"); if(button){state.id = button.dataset.id; render();}});
["#oH","#oD","#oA","#oO","#oU","#oHT","#handicapLine","#handicapHome","#handicapAway","#wMarket","#wPoisson","#wTeam"].forEach((selector)=>$(selector)?.addEventListener("input",()=>renderMain()));
$("#skipIntro").addEventListener("click",()=>$("#intro").classList.add("hide"));
setTimeout(()=>$("#intro").classList.add("hide"),3800);
$("#accountBtn").addEventListener("click", openAuth);
$("#openPaywall").addEventListener("click", openAuth);
$("#activateBtn").addEventListener("click", async ()=>{const phone = $("#phoneInput").value.trim(); const code = $("#unlockCode").value.trim(); const hint = $("#authHint"); if(!/^1\d{10}$/.test(phone)){hint.className = "auth-hint"; hint.textContent = "请输入有效的 11 位手机号。"; return;} if(!code){hint.className = "auth-hint"; hint.textContent = "请输入管理员发放的授权码。"; return;} try{hint.className = "auth-hint"; hint.textContent = "正在验证授权码..."; const response = await fetch("/api/verify-activation",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({phone,code})}); const data = await response.json(); if(!response.ok || !data.ok){hint.className = "auth-hint"; hint.textContent = data.error || "授权码无效。"; return;} localStorage.setItem("k3Phone", phone); localStorage.setItem("k3Activated", "1"); localStorage.setItem("k3ActivatedAt", new Date().toISOString()); hint.className = "auth-hint ok"; hint.textContent = "已开通当前浏览器的预测功能。"; refreshAccess(); setTimeout(()=>$("#authDialog").close(),650);}catch(error){hint.className = "auth-hint"; hint.textContent = `验证失败：${error.message}`;}});
$("#generateCodeBtn")?.addEventListener("click", async ()=>{const phone = $("#phoneInput").value.trim(); const password = $("#adminPassword").value; const result = $("#adminCodeResult"); if(!/^1\d{10}$/.test(phone)){result.className = "auth-hint"; result.textContent = "先输入用户手机号。"; return;} if(!password){result.className = "auth-hint"; result.textContent = "请输入后台口令。"; return;} try{result.className = "auth-hint"; result.textContent = "正在生成..."; const response = await fetch("/api/admin-code",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({phone,password})}); const data = await response.json(); if(!response.ok || !data.ok){result.className = "auth-hint"; result.textContent = data.error || "生成失败。"; return;} result.className = "auth-hint ok"; result.textContent = `授权码：${data.code}`; $("#unlockCode").value = data.code;}catch(error){result.className = "auth-hint"; result.textContent = `生成失败：${error.message}`;}});

render();
loadSchedule();
setInterval(loadSchedule, 30 * 60 * 1000);
$("#recordOdds")?.addEventListener("click",recordCurrentOdds);
$("#exportSamples")?.addEventListener("click",exportSamples);
$("#clearSamples")?.addEventListener("click",clearSamples);
$("#saveResult")?.addEventListener("click",saveMatchResult);
$("#toggleMonitor")?.addEventListener("click",toggleMonitor);
